FROM mdjaere/datascience-notebook-gpu
MAINTAINER Martin Jaere <martin.jaere11@imperial.ac.uk>

USER root
ENV DEBIAN_FRONTEND noninteractive
ENV OMP_NUM_THREADS 8

RUN apt-get -y update \
 && apt-get -y install \
      less \
      gnuplot \
      libnetcdf-dev \
      octave \
      liboctave-dev \
      git \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

USER jovyan
WORKDIR /home/jovyan

RUN octave --no-gui --eval "pkg install -verbose -forge -auto netcdf"
RUN octave --no-gui --eval "pkg install -verbose -forge -auto io"
RUN octave --no-gui --eval "pkg install -verbose -forge -auto statistics"

RUN pip --no-cache install octave_kernel

WORKDIR /home/jovyan/work
