FROM ubuntu:18.04 AS compile-image

WORKDIR /src

RUN apt-get update \
     && apt-get -yq install \
     gcc \
     g++ \
     gfortran \
     make \
     libblas-dev \
     liblapack-dev \
     libpcre3-dev \
     libarpack2-dev \
     libcurl4-gnutls-dev \
     epstool \
     libfftw3-dev \
     transfig \
     libfltk1.3-dev \
     libfontconfig1-dev \
     libfreetype6-dev \
     libgl2ps-dev \
     libglpk-dev \
     libreadline-dev \
     gnuplot-x11 \
     libgraphicsmagick++1-dev \
     libhdf5-serial-dev \
     openjdk-8-jdk \
     libsndfile1-dev \
     llvm-dev \
     lpr \
     texinfo \
     libgl1-mesa-dev \
     libosmesa6-dev \
     pstoedit \
     portaudio19-dev \
     libqhull-dev \
     libqrupdate-dev \
     libqscintilla2-dev \
     libsuitesparse-dev \
     texlive \
     texlive-generic-recommended \
     libxft-dev \
     zlib1g-dev \
     autoconf \
     automake \
     bison \
     flex \
     gperf \
     gzip \
     icoutils \
     librsvg2-bin \
     libtool \
     perl \
     rsync \
     tar \
     qtbase5-dev \
     qttools5-dev \
     qttools5-dev-tools \
     libqscintilla2-qt5-dev \
     wget \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*

RUN wget https://ftpmirror.gnu.org/octave/octave-5.2.0.tar.gz && \
     tar -xzf octave-5.2.0.tar.gz

RUN cd /src/octave-5.2.0 && \
     mkdir .build && \
     cd .build && \
     ./../configure --prefix=/usr/local --without-opengl && \
     make -j2 CFLAGS=-O CXXFLAGS=-O LDFLAGS= && \
     make check && \
     make install

FROM mdjaere/datascience-notebook-gpu
LABEL maintainer="Martin Jaere <martin.jaere11@imperial.ac.uk>"

# FROM https://github.com/ymatsunaga/docker-octave
# MAINTAINER Yasuhiro Matsunaga <ymatsunaga@riken.jp>

USER root
# ENV DEBIAN_FRONTEND noninteractive
# ENV OMP_NUM_THREADS 8

WORKDIR /src/octave-5.2.0/
COPY --from=compile-image /src/octave-5.2.0/ .
WORKDIR /src/octave-5.2.0/.build

RUN apt-get update \
     && apt-get -yq install \
     # less \
     # make \
     gnuplot \
     libnetcdf-dev \
     ##### octave \
     # liboctave-dev \
     # git \
     # gawk \
     gcc \
     g++ \
     gfortran \
     make \
     libblas-dev \
     liblapack-dev \
     libpcre3-dev \
     libarpack2-dev \
     libcurl4-gnutls-dev \
     epstool \
     libfftw3-dev \
     transfig \
     libfltk1.3-dev \
     libfontconfig1-dev \
     libfreetype6-dev \
     libgl2ps-dev \
     libglpk-dev \
     libreadline-dev \
     gnuplot-x11 \
     libgraphicsmagick++1-dev \
     libhdf5-serial-dev \
     openjdk-8-jdk \
     libsndfile1-dev \
     llvm-dev \
     lpr \
     texinfo \
     libgl1-mesa-dev \
     libosmesa6-dev \
     pstoedit \
     portaudio19-dev \
     libqhull-dev \
     libqrupdate-dev \
     libqscintilla2-dev \
     libsuitesparse-dev \
     texlive \
     texlive-generic-recommended \
     libxft-dev \
     zlib1g-dev \
     autoconf \
     automake \
     bison \
     flex \
     gperf \
     gzip \
     icoutils \
     librsvg2-bin \
     libtool \
     perl \
     rsync \
     tar \
     qtbase5-dev \
     qttools5-dev \
     qttools5-dev-tools \
     libqscintilla2-qt5-dev \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*

# RUN make check
RUN make install

## MDToolbox https://github.com/ymatsunaga/mdtoolbox
# path setting for octave_kernel in jupyter
# ENV OCTAVE_CLI_OPTIONS "--path /home/$NB_USER/mdtoolbox/mdtoolbox"

RUN chown $NB_USER /home/$NB_USER/*
USER $NB_USER
WORKDIR /home/$NB_USER

RUN octave --no-gui --eval "pkg install -verbose -forge netcdf" \
     && octave --no-gui --eval "pkg install -verbose -forge io" \
     && octave --no-gui --eval "pkg install -verbose -forge statistics" \
     && octave --no-gui --eval "pkg install -verbose -forge financial"

# RUN git clone https://github.com/ymatsunaga/mdtoolbox.git

# WORKDIR /home/$NB_USER/mdtoolbox
# RUN octave --no-gui --eval "make"

# # path setting for interactive octave use
# RUN echo addpath\(\'/home/$NB_USER/mdtoolbox/mdtoolbox\'\)\; >/home/$NB_USER/.octaverc

RUN pip --no-cache-dir install octave_kernel && \
     rm -rf /home/$NB_USER/.local && \
     fix-permissions $CONDA_DIR && \
     fix-permissions /home/$NB_USER

WORKDIR /home/$NB_USER
